- name: Remove Zsh & Oh-My-Zsh
  ansible.builtin.shell: rm -rf ~/.zsh ~/.oh-my-zsh

- name: Install Zsh
  ansible.builtin.apt:
    name:
      - zsh

- name: Build Oh-My-Zsh
  ansible.builtin.shell: curl -L  https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install zsh-completions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions

- name: Install zsh-history-substring-search
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-history-substring-search.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Install theme
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k'
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

- name: Update zsh config & chnage shell
  ansible.builtin.shell: |
    sed -i 's/^ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/' ~/.zshrc
    sed -i 's/^plugins=.*/plugins=(git ssh-agent zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting)/' ~/.zshrc
    sed -i '/^plugins=.*/a zstyle :omz:plugins:ssh-agent identities id_git' ~/.zshrc
    sudo chsh -s $(which zsh) $(whoami)
